version: '3.8'

services:
  postgres:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"

  mariadb:
    container_name: mariadb-container
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MARIADB_DATABASE: test
    ports:
      - "3307:3306"

  mysql:
    container_name: mysql-container
    platform: linux/x86_64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
